spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: shannee_ahirwar_ftc
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
